create table organization_categories
(
    id       integer not null
        constraint organization_categories_organization_id_fk
            references organization2,
    category varchar
);

INSERT INTO organization_categories (id, category) VALUES (250822, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250799, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250725, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (306004, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250755, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250691, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250800, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (352976, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (253841, 'null');
INSERT INTO organization_categories (id, category) VALUES (352146, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250674, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250746, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250757, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (250767, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250838, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250785, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250782, 'null');
INSERT INTO organization_categories (id, category) VALUES (250819, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (354563, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250790, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250676, 'null');
INSERT INTO organization_categories (id, category) VALUES (335753, 'Political Groups');
INSERT INTO organization_categories (id, category) VALUES (250873, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (291526, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250685, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250872, 'Business');
INSERT INTO organization_categories (id, category) VALUES (352596, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250684, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (250698, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250762, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (333337, 'Business');
INSERT INTO organization_categories (id, category) VALUES (250809, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250826, 'null');
INSERT INTO organization_categories (id, category) VALUES (250883, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (250718, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250666, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250706, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250770, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250689, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250677, 'null');
INSERT INTO organization_categories (id, category) VALUES (250707, 'null');
INSERT INTO organization_categories (id, category) VALUES (325988, 'Political Groups');
INSERT INTO organization_categories (id, category) VALUES (349627, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250709, 'null');
INSERT INTO organization_categories (id, category) VALUES (326699, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250682, 'Greek Groups');
INSERT INTO organization_categories (id, category) VALUES (250814, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (336555, 'Business');
INSERT INTO organization_categories (id, category) VALUES (250781, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250868, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (352348, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (346134, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250795, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250700, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250673, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250680, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250816, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250879, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250683, 'null');
INSERT INTO organization_categories (id, category) VALUES (250679, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250736, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250804, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250847, 'Business');
INSERT INTO organization_categories (id, category) VALUES (250773, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250687, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (335688, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250824, 'Language Groups');
INSERT INTO organization_categories (id, category) VALUES (250774, 'Political Groups');
INSERT INTO organization_categories (id, category) VALUES (342602, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250865, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (342810, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250749, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250855, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250882, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250675, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250672, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250845, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (304062, 'Business');
INSERT INTO organization_categories (id, category) VALUES (250688, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (352662, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250701, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250821, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250705, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250777, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250763, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (350750, 'Business');
INSERT INTO organization_categories (id, category) VALUES (291918, 'Service and Volunteering');
INSERT INTO organization_categories (id, category) VALUES (250759, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (347439, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (346554, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250723, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250690, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (303851, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (330755, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250833, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (260726, 'null');
INSERT INTO organization_categories (id, category) VALUES (250715, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (250871, 'null');
INSERT INTO organization_categories (id, category) VALUES (250714, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250765, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250787, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (290162, 'Honorary Groups');
INSERT INTO organization_categories (id, category) VALUES (250869, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250807, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250854, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (355297, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250670, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250779, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (250783, 'null');
INSERT INTO organization_categories (id, category) VALUES (250772, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250803, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (250792, 'null');
INSERT INTO organization_categories (id, category) VALUES (250744, 'Greek Groups');
INSERT INTO organization_categories (id, category) VALUES (250741, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250748, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250806, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250764, 'Spiritual Groups');
INSERT INTO organization_categories (id, category) VALUES (250699, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250832, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250678, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250811, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (239902, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250798, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250839, 'null');
INSERT INTO organization_categories (id, category) VALUES (250692, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (335822, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (296867, 'Political Groups');
INSERT INTO organization_categories (id, category) VALUES (291527, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250722, 'Business');
INSERT INTO organization_categories (id, category) VALUES (250884, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250756, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250889, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250733, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (353272, 'Pre-Professional Groups');
INSERT INTO organization_categories (id, category) VALUES (277844, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250753, 'Language Groups');
INSERT INTO organization_categories (id, category) VALUES (250734, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (250874, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250703, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250760, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (255745, 'null');
INSERT INTO organization_categories (id, category) VALUES (250862, 'null');
INSERT INTO organization_categories (id, category) VALUES (250743, 'null');
INSERT INTO organization_categories (id, category) VALUES (250843, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250793, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250713, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250697, 'null');
INSERT INTO organization_categories (id, category) VALUES (250668, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250669, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250726, 'null');
INSERT INTO organization_categories (id, category) VALUES (250829, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250827, 'null');
INSERT INTO organization_categories (id, category) VALUES (250776, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250731, 'null');
INSERT INTO organization_categories (id, category) VALUES (250842, 'null');
INSERT INTO organization_categories (id, category) VALUES (250789, 'Greek Groups');
INSERT INTO organization_categories (id, category) VALUES (250888, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250761, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250818, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250739, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250885, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250730, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250711, 'International Groups');
INSERT INTO organization_categories (id, category) VALUES (250870, 'null');
INSERT INTO organization_categories (id, category) VALUES (250710, 'Multi-Cultural Groups');
INSERT INTO organization_categories (id, category) VALUES (250864, 'Greek Groups');
INSERT INTO organization_categories (id, category) VALUES (250728, 'null');
INSERT INTO organization_categories (id, category) VALUES (335141, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (352975, 'Arts Groups');
INSERT INTO organization_categories (id, category) VALUES (332119, 'Advocacy and Activism Groups');
INSERT INTO organization_categories (id, category) VALUES (250766, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250812, 'Academic Groups');
INSERT INTO organization_categories (id, category) VALUES (250702, 'Academic Groups');
